### ISSUE TITLE
Screenshots folder, <a> link, and <img> src

### ISSUE THREAD

**Issue by eduard-chai** [Kenzitron/protractor-jasmine2-html-reporter#11]
There is a issue with creating screenshots folder, `<a>` link, and `<img>` src.
- Screenshot folder

``` javascript
screenshotPath = path.join(self.savePath + self.screenshotsFolder, spec.screenshot);
```

should be:

``` javascript
screenshotPath = path.join(self.savePath + '/' + self.screenshotsFolder, spec.screenshot);
```
- `<a>` link

``` javascript
html += '<a href="' + self.screenshotsFolder + '/' + spec.screenshot + '">';
```

should be:

``` javascript
html += '<a href="' + self.screenshotsFolder + spec.screenshot + '">';
```
- `<img>` src

``` javascript
html += '<img src="' + self.screenshotsFolder + '/' + spec.screenshot + '" width="100" height="100" />';
```

should be:

``` javascript
html += '<img src="' + self.screenshotsFolder + spec.screenshot + '" width="100" height="100" />';
```

Cheers

**Comment by Kenzitron** [comment]
Which one is the error that you have found?

**Comment by eduard-chai** [comment]
The screenshot folder and img src link. Using your code, i get "reportscreenshot" as the screenshot folder where it should be "report/screenshot". This make all the images link in report.html broken.

As the img link, not a big issue. You have extra "\" in your `img src`. Even though it is still working, i think it is cleaner to remove the extra "\".

Cheers

**Comment by eduard-chai** [comment]
Anyway, i have forked my version with the fix. Please take a look.
