### ISSUE TITLE
Final "Tests Passed:" value is passed as NULL

### ISSUE THREAD

**Issue by brentmagstadt** [Kenzitron/protractor-jasmine2-html-reporter#12]
I just installed this awesomely helpful package; it's totally made my life easier. However, no matter what suites I run, singles or multiples, I always get the final result at the bottom of the html page as: 
Tests passed: NaN%

Even though all tests have passed throughout.

**Comment by Kenzitron** [comment]
What are you experiencing? I can not help you with that information, sorry.

**Comment by shoaibuddin** [comment]
Having same issue for last 2 iteration : Tests passed: NaN%

**Comment by Kenzitron** [comment]
I can not reproduce this error. I am trying to do it with the tests included in the plugin but everything is working as expected.

Could you add additional information such an example of code that leads to that error?

**Comment by mattc41190** [comment]
This is happening to me as well.

**Comment by 5c7** [comment]
The percentage is based to on validations. Implement some "toEqual" for validations.

**Comment by Kexone** [comment]
I have the same problem. When I testing only one suite of specs all is okay, when I testing more suites happens this problem In all specs I using expected conditions.
[one_suite.pdf](https://github.com/Kenzitron/protractor-jasmine2-html-reporter/files/339000/one_suite.pdf)
[all_suites.pdf](https://github.com/Kenzitron/protractor-jasmine2-html-reporter/files/339001/all_suites.pdf)

**Comment by JSlain** [comment]
Maybe late, but @5c7 comment is right...
This happens if you have a `it(){}` without any `expect()`.

**Comment by Kenzitron** [comment]
This has been already fixed by PR 45 by @vasanth5738
