### ISSUE TITLE
Is there a possible way to generate separate reports for multi browser testing (multiCapabilities)?

### ISSUE THREAD

**Issue by vrpruthvi** [Kenzitron/protractor-jasmine2-html-reporter#13]
Thanks for great tool mate. Is there a possible way to generate separate reports for multi browser testing?

**Comment by Kenzitron** [comment]
I have not thought about it. But I think that is something that should be possible.

Let me check it and see how and when can be implemented :)

**Comment by iljapavlovs** [comment]
Yes, this is also very desired feature!

**Comment by patcyg** [comment]
@vrpruthvi Following trick should work for you. Following snippet will create browser based report. 

Keep this code in config.js

```
onPrepare: function() {
    var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
    browser.getProcessedConfig().then(function(config) {
      var capabilities = config.capabilities;
      jasmine.getEnv().addReporter(
        new Jasmine2HtmlReporter({
          savePath: appRoot + '/reports/',
          screenshotsFolder: '/screenshots',
          filePrefix: 'protractor-demo-tests-report-' + capabilities.platform + '-' + capabilities.browserName,
          consolidateAll: true,
          takeScreenshotsOnlyOnFailures: true,
        })
      );
    });
  },
```

**Comment by tyaga001** [comment]
Hi @patcyg , I tried to generate reports for multi-browsers but looks like it only generate one blank html report when i use above solution. Could you please take a look what wrong i am doing here. 
please help.

 ```
 onPrepare: function () {

    browser.manage().timeouts().implicitlyWait(11000);
    var width = 768;
    var height = 1366;
    browser.driver.manage().window().setSize(768, 1366);
    browser.ignoreSynchronization = false;


      browser.getProcessedConfig().then(function (config) {
        var capabilities = config.capabilities;
        var today = new Date();
        var timeStamp = today.getMonth() + 1 + '-' + today.getDate() + '-' + today.getFullYear() + '-' + today.getHours() + 'h-' + today.getMinutes() + 'm-' + today.getSeconds() + 's';
        jasmine.getEnv().addReporter(
          new Jasmine2HtmlReporter({
            savePath: __dirname+'/e2e' + timeStamp,
            screenshotsFolder: '/screenshots',
            filePrefix: 'protractor-report-' + capabilities.platform + '-' + capabilities.browserName,
            consolidateAll: true,
            consolidate: true,
            takeScreenshotsOnlyOnFailures: true,
            cleanDestination: true
          })
        );
      });
  },
```

**Comment by tyaga007** [comment]
@Kenzitron - Thanks for the tool Can you please look into here when we are trying to generate report for multi capabilities, it only shows single html report in target folder. please suggest.

var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
var log4js = require('log4js');
var params = process.argv;
var args = process.argv.slice(3);

exports.config = {
  //seleniumServerJar: './node_modules/gulp-protractor/node_modules/protractor/selenium/selenium-server-standalone-2.48.2.jar',
  seleniumAddress: 'http://localhost:4444/wd/hub',
  allScriptsTimeout: 100000,
  framework: 'jasmine2',

  onPrepare: function () {

    return new Promise(function(fulfill, reject) {
      browser.getCapabilities().then(function(value) {
        reportName = value.get(Math.random(8,2)) + '_' + value.get('browserName') + '_' + Math.floor(Math.random() * 1E16);
        jasmine.getEnv().addReporter(
          new Jasmine2HtmlReporter({
            //cleanDestination: false,
            savePath: __dirname+'/target',
            //docTitle: 'Web UI Test Report',
            screenshotsFolder: 'image',
            //takeScreenshots: true,
            takeScreenshotsOnlyOnFailures: true,
            consolidate: true,
            consolidateAll: true,
             preserveDirectory: true,
            //fixedScreenshotName: true,
            filePrefix: reportName + ".html"
          })
        );
        fulfill();
      });
    });

    // browser.manage().timeouts().implicitlyWait(11000);
    var width = 768;
    var height = 1366;
    browser.driver.manage().window().setSize(768, 1366);
    browser.ignoreSynchronization = false; 
  },

  afterLaunch: function afterLaunch() {
    var fs = require('fs');
    var output = '';
    fs.readdirSync('target/').forEach(function (file) {
      if (!(fs.lstatSync('target/' + file).isDirectory()))
        output = output + fs.readFileSync('target/' + file);
    });
    fs.writeFileSync('target/ConsolidatedReport.html', output, 'utf8');

  },

  suites:{

    example:['./test/e2e/specs/**/*Spec.js',]
  },


  /*  capabilities: {
      'browserName': 'chrome'
    },*/

  multiCapabilities: [
    {
      'browserName': 'chrome'
    },
    {
      'browserName': 'firefox'
    }
  ],


  resultJsonOutputFile:'./results.json',

  // Options to be passed to Jasmine-node.
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 100000
  }
};

**Comment by munivaraachari** [comment]
Hi @tyaga001, Use below code, it will work.
only  you need to change "filePrefix" tag to "fileNamePrefix", or "fileName"

onPrepare: function() {
    require('ts-node').register({ project: 'e2e' });
    browser.getProcessedConfig().then(function(config) {
      var capabilities = config.capabilities;
      jasmine.getEnv().addReporter(
        new Jasmine2HtmlReporter({
          savePath: 'testreports/report',
          **fileName:** protractor-report-' + capabilities.platform + '-' + capabilities.browserName,
          takeScreenshotsOnlyOnFailures: true
        })
      );
    });
}
