### ISSUE TITLE
Screenshots only for failed specs

### ISSUE THREAD

**Issue by koerbcm** [Kenzitron/protractor-jasmine2-html-reporter#2]
Is there some option I can set that will only take a screenshot if there is a failure? If not, can we add one?

**Comment by Kenzitron** [comment]
This is a new feature that will be taken in consideration. The next release will include this.

Thanks for the advice, It's great to see that this plugin is being used.

**Comment by koerbcm** [comment]
Thank you so much for your help! This helps us out significantly.
