### ISSUE TITLE
screenshotsFolder doesn't work

### ISSUE THREAD

**Issue by carantes** [Kenzitron/protractor-jasmine2-html-reporter#24]
When i try to config the screenshotsFolder property, the generated folder name is always concatenated with the savePath folder name and always on the same level.

htmlReporter = new Jasmine2HtmlReporter({
      savePath: 'tests/e2e/screenshots',
      screenshotsFolder: 'images',
      fixedScreenshotName: true
    })

Result:
tests/e2e/screenshots
tests/e2e/screenshotsimages

**Comment by s10mcow** [comment]
+1

**Comment by s10mcow** [comment]
@carantes Change Line Number 167 index.js to this:

screenshotPath = path.join(self.savePath + '/' + self.screenshotsFolder, spec.screenshot);

**Comment by s10mcow** [comment]
Pull Request Submitted @carantes @Kenzitron

**Comment by Kenzitron** [comment]
I would like to point that in the readme you see the savePath value always with '/' at the end, that makes the folder structure work. If everyone is using that notation, when we introduce this change will affect them.

@carantes, have you tried with the next configuration?:

```
htmlReporter = new Jasmine2HtmlReporter({
savePath: 'tests/e2e/screenshots/',
screenshotsFolder: 'images',
fixedScreenshotName: true
})
```

If that works I should close the PR without accepting it. Anyways, @stenmuchow thanks you so much for your collaboration and support :)

**Comment by s10mcow** [comment]
@Kenzitron Sounds good, close away... But it seems that this part is not very intuitive and would cause confusion again in the future.

In my opinion the code needs to be more defensive that it currently is - accepting both ways of defining a path with and without the '/.'

**Comment by carantes** [comment]
@Kenzitron @stenmuchow thanks for the help, i forgot the slash "/" on the end of savePath.

**Comment by Kenzitron** [comment]
Ok, maybe the pull request should be in that line. check if we have the /
at the end and include it or remove it accordingly.

Do you agree?

**Comment by s10mcow** [comment]
I think it can only help to make the user’s life easier!

**Comment by gologox** [comment]
This is still occurring for me on Protractor 3.3.0 with the latest version of this module. Any ideas on how to fix?

`htmlReporter = new Jasmine2HtmlReporter({
         savePath: 'xmloutput/local/core/screenshots/',
         takeScreenshotsOnlyOnFailures: true,
         screenshotsFolder: 'images',
         filePrefix: 'report'
});`

It creates a folder called screenshotsimages.
