### ISSUE TITLE
When running specs, getting warning at startup

### ISSUE THREAD

**Issue by koerbcm** [Kenzitron/protractor-jasmine2-html-reporter#5]
When I run a spec, I get the following warning 'problem trying to remove a folder' at the launch of the test. If I disable the html reporter, the warning stops. I don't know what the problem is and it doesn't seem to affect a successful outcome, but would like to know why it is happening. 

**Test Result Outcome**
/usr/bin/node /home/XXXX/node_modules/protractor/lib/cli.js /home/XXXX/workspace/ui/src/config/config.js
Using the selenium server at http://localhost:4444/wd/hub
[launcher] Running 1 instances of WebDriver
Spec started
_problem trying to remove a folder_

  1 To validate breadcrumbs

**Config**

```
var today = new Date(),
timeStamp = today.getFullYear() + '-' + today.getMonth() + 1 + '-' + today.getDate() + '_' +        today.getHours() + '-' + today.getMinutes() + '-' + today.getSeconds();
var path = require('path');
var reportPath = path.join(__dirname, "/../../reports");
var htmlReportPath = path.join(reportPath, "html_report/" + timeStamp + "/");
var xmlReportPath = path.join(reportPath, "xml_report/" + timeStamp + "/");

var SpecReporter = require('jasmine-spec-reporter');
    // add jasmine spec reporter
    jasmine.getEnv().addReporter(new SpecReporter({
        displayStacktrace: false,     // display stacktrace for each failed assertion
        displayFailuresSummary: true, // display summary of all failures after execution
        displaySuccessfulSpec: true,  // display each successful spec
        displayFailedSpec: true,      // display each failed spec
        displayPendingSpec: true,    // display each pending spec
        displaySpecDuration: true,   // display each spec duration
        displaySuiteNumber: true,    // display each suite number (hierarchical)
        colors: {
            success: 'green',
            failure: 'red',
            pending: 'cyan'
        },
        prefixes: {
            success: '✓ ',
            failure: '✗ ',
            pending: '- '
        }
    }));

    var jasmineReporters = require('jasmine-reporters');
    var HtmlScreenshotReporter = require('protractor-jasmine2-html-reporter');
    jasmine.getEnv().addReporter(new jasmineReporters.JUnitXmlReporter({
        consolidateAll: true,
        filePrefix: 'xmloutput',
        savePath: xmlReportPath
    }));

    jasmine.getEnv().addReporter(
        new HtmlScreenshotReporter({
            savePath: htmlReportPath,
            filename: 'Report.html',
            takeScreenshots: true,
            takeScreenshotsOnlyOnFailures: true
        }));
```

**Comment by Kenzitron** [comment]
This happens because the plugin tries to removes the previous report generated.

**Comment by mbielski** [comment]
I get the same warning. Maybe it should check to see if the previous report exists before it tries to remove it?

**Comment by allspat** [comment]
Following function in **<module_path>protractor-jasmine2-html-reporter/index.js** is the culprit.

### function rmdir(dir) {

```
try {
    var list = fs.readdirSync(dir);
    for (var i = 0; i < list.length; i++) {
        var filename = path.join(dir, list[i]);
        var stat = fs.statSync(filename);

        if (stat.isDirectory()) {
            // rmdir recursively
            rmdir(filename);
        } else {
            // rm fiilename
            fs.unlinkSync(filename);
        }
    }
    fs.rmdirSync(dir);
}catch (e) { log("problem trying to remove"); }
```

};

You can simply make the catch block to print empty log e.g. log("") or change it to "catch (e) { log("problem trying to remove" +dir); }" to know what directory its trying to remove

**Comment by Kenzitron** [comment]
Included in pull request  #21

**Comment by FintanK** [comment]
Doesn't look like this issue was resolved. I still experience it with version 0.0.6 when running new tests.

e.g. console error around the generated screenshots.

"problem trying to remove a folder: C:\Users\user\Projects\project-namei/test_results/e2e/screenshots/1475144878817/"

**Comment by solomonoshortia** [comment]
same here

**Comment by Mithun048** [comment]
Hi,
Even i am getting the same error in deleting the existing folder and try creating again.

**Comment by sergiybuch** [comment]
Same here
