### ISSUE TITLE
HTML report is generated but no screenshots

### ISSUE THREAD

**Issue by vsathyak** [Kenzitron/protractor-jasmine2-html-reporter#7]
Hi,

I would like to let you know that I am getting the report but no screenshots are generated. Please see my conf.js reporter config..

var Jasmine2HtmlReporter = require('C:/NodeModules/node_modules/protractor-jasmine2-html-reporter');

 jasmine.getEnv().addReporter(new Jasmine2HtmlReporter({
            savePath: 'C:/ApolloReports/Reports',
            screenshotsFolder: 'C:/ApolloReports/ScreenShots',
            takeScreenshots: true,
            //takeScreenshotsOnlyOnFailures: true,
            filePrefix: 'protractor-tests-report'
            //consolidate: false,
            //consolidateAll: false
        }));
![report with no screenshot](https://cloud.githubusercontent.com/assets/8452825/8480615/a3b53cc0-20ac-11e5-9b10-03ab64f328d2.jpg)

**Comment by mbielski** [comment]
I am having this same issue. My tests currently run on IE11, but support for Chrome and FF is in the works. We expect test reports to go out to customers, so the missing screenshots is a big issue for us.

**Comment by greyarch** [comment]
Same issue here - the report.html is created, but the screenshot png files are not.
Environment:
  Ubuntu 14.04
  nodejs 0.12.7
  protractor 2.2.0

**Comment by drmikecrowe** [comment]
I thought I could fix this by adding a processTick in the code, but couldn't figure out how.

To resolve, simply add this to your test spec:

```
afterAll(function(done){
    process.nextTick(done);
});
```

https://github.com/angular/protractor/issues/1753

**Comment by charlotte74** [comment]
I'm having a similar issue - the sreenshots are supposedly being taken but they are completely white... I have tried adding the process.nextTick(done) as mentioned, but this didn't help

**Comment by justengland** [comment]
I am seeing a similar problem, my screenshots are generated, but the html contains a double slash, which causes the image not to render.

```
<a href="images//147deedab06641f825408a6ddf769a16.png">
```

I have tried serveral configurations, but they all have the double slash

```
    jasmine.getEnv().addReporter(new Jasmine2HtmlReporter({
            savePath: './results/',
            screenshotsFolder: 'images'
        }));
```

**Comment by bytesofdhiren** [comment]
Update index.js with. It will solve the problem. I am not able to checkin else I would have done it. 

`screenshotPath = path.join(self.savePath + "/" + self.screenshotsFolder, spec.screenshot);`

function

**Comment by rojosa** [comment]
any other solution? what if none of the above works? tried everything, the report is generated but no screenshots, any help would be appreciated

**Comment by Rahul-012** [comment]
Thanks a lot guys i have fixed this Problem now reports are generated with Image !!!!
![screenshot 148](https://cloud.githubusercontent.com/assets/17723293/16584966/2383666e-42dc-11e6-9cbb-4585923b0d83.png)

**Comment by krisqa** [comment]
@Rahul-012 

I have been trying to implement it but no luck.
Can you please share the code So, I can try my luck with it. -- Thanks
Please forward it to -- hkrisp@gmail.com

**Comment by Rahul-012** [comment]
@krisqa 
Yes definately i'll send it to your mail id

**Comment by Rahul-012** [comment]
@rojosa  
tell me what Problem you are facing

**Comment by rojosa** [comment]
@Rahul-012 

hey, the issue was solved,there was a problem with my spec file so made the necessary changes and it started working fine, Thanks

**Comment by ghost** [comment]
thanks, I just added the line 

screenshotPath = path.join(self.savePath + "/" + self.screenshotsFolder, spec.screenshot);

Under the following section in the Index.js file:
  //Take screenshots taking care of the configuration
        if ((self.takeScreenshots && !self.takeScreenshotsOnlyOnFailures) ||
            (self.takeScreenshots && self.takeScreenshotsOnlyOnFailures && isFailed(spec))) {
            if (!self.fixedScreenshotName)
                spec.screenshot = hat() + '.png';
            else
                spec.screenshot = sanitizeFilename(spec.description) + '.png';

```
        browser.takeScreenshot().then(function (png) {
            browser.getCapabilities().then(function (capabilities) {
                var screenshotPath;

                //Folder structure and filename
                screenshotPath = path.join(self.savePath + "/" + self.screenshotsFolder, spec.screenshot);

                mkdirp(path.dirname(screenshotPath), function (err) {
                    if (err) {
                        throw new Error('Could not create directory for ' + screenshotPath);
                    }
                    writeScreenshot(png, screenshotPath);
                });
            });
        });
    }
```

just updated that screenshotPath and it worked!
